spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        spring:



  datasource:
    url: jdbc:postgresql://localhost:5432/boothouse?sslmode=disable&charSet=UTF-8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

logging.level:
  org.hibernate.sql: debug
  org.hibernate.type: trace

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /